[Manager]
# HIVE systemd system configuration
DefaultTimeoutStartSec=30s
DefaultTimeoutStopSec=30s
DefaultRestartSec=10s
DefaultLimitNOFILE=65536
DefaultLimitNPROC=512

# Personality-aware management
EnableJoinController=no
JoinControllers=cpu,cpuacct,memory
